function edu_rss() {
document.write("<div id=\"SubTitleText\">Edu_RSS</div><div id=\"InfoText\"><a href=\"http://www.downes.ca/cgi-bin/xml/edu_rss.cgi\" class=\"Troll\"><br />Edu_RSS</a> is updated every hour. Aggregated by Stephen Downes</p>");
   document.write("<p> <a href=\"http://www.wired.com/news/columns/0,72395-0.html?tw=rss.index\">All Hail the Mighty Coffee Bean! </a><br />If your morning cup of joe is maniacally important to you, consider the exciting caffeine technology that is just around the bend. Commentary by Lore Sj&amp;#246;berg. From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=29\" class=\"Troll\">Wired News</a> on January 3, 2007 at 6:45 a.m.</p>");
   document.write("<p> <a href=\"http://www.wired.com/news/columns/0,72394-0.html?tw=rss.index\">Legal Predictions for 2007 </a><br />Congress and the courts will take on some thorny tech issues in the coming year. Here are the two that will loom largest, and the likely outcomes. Commentary by Jennifer Granick. From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=29\" class=\"Troll\">Wired News</a> on January 3, 2007 at 6:45 a.m.</p>");
   document.write("<p> <a href=\"http://www.wired.com/wired/archive/15.01/start.html?pg=5\">What's Inside: Nondairy Creamer </a><br />This coffee-bar staple is off-limits to vegans and could potentially explode. By Patrick Di Justo from Wired magazine. From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=29\" class=\"Troll\">Wired News</a> on January 3, 2007 at 6:45 a.m.</p>");
   document.write("<p> <a href=\"http://www.wired.com/wired/archive/15.01/alive.html\">Li'l Robot Dinosaur Comes to Life </a><br />Meet Pleo, the snuffling, stretching, oddly convincing robotic dinosaur. You are so going to want one. By Clive Thompson from Wired magazine. From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=29\" class=\"Troll\">Wired News</a> on January 3, 2007 at 6:45 a.m.</p>");
   document.write("<p> <a href=\"http://www.wired.com/news/technology/0,72371-0.html?tw=rss.index\">Where to Catch Some Wi-Fi Waves </a><br />From Waikiki to Miami, the number of beaches offering wireless internet access is growing every year. Here's a rundown of the hottest spots for surfside Wi-Fi (just in case you're determined to ruin your vacation). By Marty Graham. From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=29\" class=\"Troll\">Wired News</a> on January 3, 2007 at 6:45 a.m.</p>");
   document.write("<p> <a href=\"http://www.hyperorg.com/blogger/mtarchive/fastforward_blog.html\">FastForward blog     </a><br />I've added the FastForward blog to my blogroll because it's got an excellent list of contributors and has been posting some very interesting stuff if you care about folksonomies, KM, \"enterprise 2.0\" (oy), etc. (Also, I get to use the little auto-blogroll creator I wrote over the weekend to make it easier to update Dan Bricklin's blogrolling javascript.) But, I owe some disclosure on it: The blog is produced to support the FastForward event, a conference sponsored by Fast Search. I spoke at an executive seminar Fast put on a few months ago, and I may be doing some form...     From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=64\" class=\"Troll\">Joho the Blog</a> on January 3, 2007 at 3:48 a.m.</p>");
   document.write("<p> <a href=\"http://www.hyperorg.com/blogger/mtarchive/ephemeral_selves_not_selves_fu.html\">Ephemeral selves, not selves, future selves, balding portly selves     </a><br />danah notes: Many teens are content (if not happy) to start over with most of their accounts in most places. Forgot your IM password? Sign up again. Forgot your email address? Create a new one. Forgot your login? Time for a change. This is so fascinating. Us middle-aging bloggers who think blogs are about building selves in the new public are apparently not speaking for anyone other than us middle-aging bloggers. Maybe Web presence for the young'uns has little to do with building selves or maybe the nature of that public self is so different from the corporeal one the...     From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=64\" class=\"Troll\">Joho the Blog</a> on January 3, 2007 at 3:48 a.m.</p>");
   document.write("<p> <a href=\"http://www.hyperorg.com/blogger/mtarchive/wiinjury.html\">Wiinjury     </a><br />A friend of mine thinks she may have sprained her back playing with the Nintendo Wii. This would be one of the first documented cases of a Wiinjury&amp;amptrade;. [Tags: wiinjury wii games]...     From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=64\" class=\"Troll\">Joho the Blog</a> on January 3, 2007 at 3:48 a.m.</p>");
   document.write("<p> <a href=\"http://feeds.feedburner.com/~r/interfacedesignorg/~3/70111363/owrede\">Links for 2007-01-02 [del.icio.us] </a><br /> <a class=\"Troll\" href=\"http://lesliefranke.com/files/reference/csscheatsheet.html\">CSS Cheat Sheet</a> <a class=\"Troll\" href=\"http://www.emuscene.com/\">Emuscene</a>  From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=47\" class=\"Troll\">owrede_log</a> on January 3, 2007 at 2:47 a.m.</p>");
   document.write("<p> <a href=\"http://www.nytimes.com/2007/01/03/business/media/03fresh.html?ex=1325480400&en=cd09d29371936ce7&ei=5090&partner=rssuserland&emc=rss\">Advertising: Sensing Opportunity in Dormitory Air </a><br />Younger customers are at the forefront of a boom in air fresheners as companies pour money into advertisements making the products seem cool. From <a href=\"http://www.downes.ca/cgi-bin/xml/feeds.cgi?feed=20\" class=\"Troll\">New York Times: Education</a> on January 3, 2007 at 2:45 a.m.</p>");
   document.write("</div>");
}
edu_rss();
